name: test

on:
  push:
    branches:
      - main
      - dev
      - "feature/*"
      - "features/*"
      - "feature/*"
      - "features/*"
  pull_request:
    branches:
      - main
      - dev
      - "feature/*"
      - "features/*"
      - "feature/*"
      - "features/*"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Install dependencies
        run: |
          forge soldeer update
        id: install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
